name: Publish Development UAT Builds (Firebase App Distribution)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      JAVA_OPTS: "-Xmx3g"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Gradle
        run: ./gradlew clean --no-daemon

      - name: Decode and create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

#      # Create google-services file
#      - name: Create file
#        run: cat /home/runner/work/news-shots-android-app/news-shots-android-app/app/google-services.json | base64
#
#      # Update google-services file
#      - name: Update data
#        env:
#          DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
#        run: echo $DATA > /home/runner/work/news-shots-android-app/news-shots-android-app/app/google-services.json

      - name: Generate keystore.properties
        env:
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        run: |
          cat <<EOF > keystore.properties
          storePassword:$KEYSTORE_STORE_PASSWORD
          keyPassword:$KEYSTORE_KEY_PASSWORD
          keyAlias:$KEYSTORE_KEY_ALIAS
          storeFile:${{ vars.KEYSTORE_STORE_FILE_PATH }}
          EOF

      - name: Decode keystore and create jks
        env:
          KEYSTORE_JKS_BASE64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
        run: echo "$KEYSTORE_JKS_BASE64" | base64 --decode > ./app/android.keystore

      - name: Build Project All countries UAT
        run: ./gradlew assembleUatRelease --no-daemon -Dorg.gradle.jvmargs="-Xmx3g -Dorg.gradle.workers.max=2" --info

      - name: Upload UAT artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        env:
          FIREBASE_APP_ID_UAT: ${{ secrets.FIREBASE_APP_ID_UAT }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        with:
          appId: $FIREBASE_APP_ID_UAT
          serviceCredentialsFileContent: $FIREBASE_CREDENTIALS
          file: app/build/outputs/apk/uat/release/app-uat-release.apk
          releaseNotes: "Build flavour: UAT Release from main ### Changelog: ${{ github.event.head_commit.message }}"
          groups: "QA"